version: '3'
services:
  nginx:
    image: estoult_fr-nginx
    container_name: estoult_fr-nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: no
    volumes:
      - build:/build
      - letsencrypt:/etc/letsencrypt

  front:
    image: estoult_fr-front
    container_name: estoult_fr-front
    build: .
    restart: no
    volumes:
      - build:/build
    depends_on:
      - nginx

volumes:
  build:
  letsencrypt: