version: '3'
services:
  nginx:
    image: estoult_fr-nginx
    container_name: estoult_fr-nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: no
    volumes:
      - build:/build
      - letsencrypt:/etc/letsencrypt

  front_builder:
    image: estoult_fr-front_builder
    container_name: estoult_fr-front_builder
    build: .
    restart: no
    volumes:
      - build:/build
      - git-repo:/app/estoult.fr

volumes:
  git-repo:
  build:
  letsencrypt: