version: '3'
services:
  git_puller:
    image: estoult_fr-git_puller
    container_name: estoult_fr-git_puller
    build: .
    restart: no
    volumes:
      - git-repo:/estoult.fr

  # nginx:
  #   image: estoult_fr-nginx
  #   container_name: estoult_fr-nginx
  #   build: .
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   depends_on:
  #     - git_puller
  #   volumes:
  #     - git-repo:/estoult.fr
  #     - build:/build
  #     - letsencrypt:/etc/letsencrypt

  front_builder:
    image: estoult_fr-front_builder
    container_name: estoult_fr-front_builder
    build: .
    restart: no
    depends_on:
      - git_puller
    volumes:
      - git-repo:/estoult.fr
      - build:/build

volumes:
  git-repo:
  build:
  letsencrypt: