version: '3'
services:
  git_puller:
    image: estoult_fr-git_puller
    container_name: estoult_fr-git_puller
    build: .
    restart: no
    volumes:
      - git-repo:/estoult.fr

  front_builder:
    image: estoult_fr-front_builder
    container_name: estoult_fr-front_builder
    build: .
    restart: no
    depends_on:
      git_puller:
        condition: service_completed_successfully
    volumes:
      - git-repo:/estoult.fr
      - build:/build

  nginx:
    image: estoult_fr-nginx
    container_name: estoult_fr-nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      front_builder:
        condition: service_completed_successfully
    volumes:
      - git-repo:/estoult.fr
      - build:/build
      - letsencrypt:/etc/letsencrypt



volumes:
  git-repo:
  build:
  letsencrypt: